[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "627eecb5c3e54a81fb4f4fa768c2c9d04b6ff782"
lazy = true
libc = "glibc"
llvm_version = "14"
os = "linux"

    [[pocl.download]]
    sha256 = "850f05ad8ab8923d08ad8547d0d0167c417661b1eb61fdf55bf7584a0af21460"
    url = "https://github.com/maleadt/pocl_jll.jl/releases/download/pocl-v6.0.0+6/pocl.v6.0.0.x86_64-linux-gnu-cxx11-llvm_version+14.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "300c91aa22ae5365f0b7a0087420d28545910692"
lazy = true
libc = "glibc"
llvm_version = "14.asserts"
os = "linux"

    [[pocl.download]]
    sha256 = "fcf1b02fafab71f8c1765a1cb5c898745737e55161e7cd744344b15edc2635d1"
    url = "https://github.com/maleadt/pocl_jll.jl/releases/download/pocl-v6.0.0+6/pocl.v6.0.0.x86_64-linux-gnu-cxx11-llvm_version+14.asserts.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7e762dcd1a12f38876c5fb10b82e13741b15b98"
lazy = true
libc = "glibc"
llvm_version = "16"
os = "linux"

    [[pocl.download]]
    sha256 = "251d18cb73dcff6dd60915d49e76b9128cecea8c65b6f17fd54a4edec984d72b"
    url = "https://github.com/maleadt/pocl_jll.jl/releases/download/pocl-v6.0.0+7/pocl.v6.0.0.x86_64-linux-gnu-cxx11-llvm_version+16.tar.gz"
